name: egano
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^0.8.3
  url_launcher: ^6.0.20
  google_fonts: ^6.2.1
  intl: ^0.17.0
  permission_handler: ^10.0.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Tektur
      fonts:
        - asset: packages/uas_pab_main/fonts/Tektur.ttf
          weight: 400
    - family: Oxanium
      fonts:
        - asset: packages/uas_pab_main/fonts/Oxanium.ttf
          weight: 700
