name: egano
description: "An application that merges cryptography and steganography into a piece by using Caesar Cipher and LSB method."
publish_to: 'none'
version: 1.2.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^0.8.3
  url_launcher: ^6.0.20
  google_fonts: ^6.2.1
  cupertino_icons: ^1.0.8
  permission_handler: ^10.0.0
  shared_preferences: ^2.0.6
  intl: ^0.17.0
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.9.2
  
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/icon.png"

flutter:
  uses-material-design: true
  fonts:
    - family: Tektur
      fonts:
        - asset: packages/egano/fonts/Tektur.ttf
          weight: 400
    - family: Oxanium
      fonts:
        - asset: packages/egano/fonts/Oxanium.ttf
          weight: 700